kind: pipeline
type: docker
name: rebuild-builder-rust-aarch64-xenial

trigger:
  branch:
  - master

steps:
- name: build rust-aarch64-xenial
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/rust-aarch64-xenial
    tags:
    - latest
    context: ./aarc64/
    registry: docker-registry.k8s.array21.dev
- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust builders
  when:
    status: [ failure ]
---
kind: pipeline
type: docker
name: rebuild-builder-rust-armhf-xenial

trigger:
  branch:
  - master

steps:
- name: build rust-armhf-xenial
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/rust-armhf-xenial
    tags:
    - latest
    context: ./armhf/
    registry: docker-registry.k8s.array21.dev
- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust builders
  when:
    status: [ failure ]
---
kind: pipeline
type: docker
name: rebuild-builders-rust-amd64-darwin

trigger:
  branch:
  - master

steps:
- name: build rust-amd64-darwin
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/rust-amd64-darwin
    tags:
    - latest
    context: ./x86_64/darwin/
    registry: docker-registry.k8s.array21.dev
- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust builders
  when:
    status: [ failure ]
---
kind: pipeline
type: docker
name: rebuild-builders-rust-amd64-xenial

trigger:
  branch:
  - master

steps:
- name: build rust-amd64-xenial
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/rust-amd64-xenial
    tags:
    - latest
    context: ./x86_64/xenial/
    registry: docker-registry.k8s.array21.dev
- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust builders
  when:
    status: [ failure ]
---
kind: pipeline
type: docker
name: rebuild-builder-rust-base 

trigger:
  branch:
  - master

steps:
- name: build rust-base
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/rust-base 
    tags:
    - latest
    context: ./x86_64/ci/
    registry: docker-registry.k8s.array21.dev
- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust builders
  when:
    status: [ failure ]
---
kind: pipeline
type: docker
name: rebuild-builder-rust-amd64-centos7

trigger:
  branch:
  - master

steps:
- name: build rust-amd64-centos7
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/rust-amd64-centos7
    tags:
    - latest
    context: ./x86_64/centos7/
    registry: docker-registry.k8s.array21.dev
- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust builders
  when:
    status: [ failure ]