kind: pipeline
type: docker
name: aarch64-xenial

trigger:
  branch:
  - master

steps:
- name: build rust-aarch64-xenial
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/rust-aarch64-xenial
    tags:
    - latest
    dockerfile: ./aarch64/Dockerfile
    context: ./aarch64/
    registry: docker-registry.k8s.array21.dev

- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust-Docker-Builders
  when:
    status: [ failure ]
---
kind: pipeline
type: docker
name: armhf-xenial

steps:
- name: build rust-armhf-xenial
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/rust-armhf-xenial
    tags:
    - latest
    dockerfile: ./armhf/Dockerfile
    context: ./armhf/
    registry: docker-registry.k8s.array21.dev

- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust-Docker-Builders
  when:
    status: [ failure ]
---
kind: pipeline
type: docker
name: amd64-darwin

depends_on:
- generic-darwin

steps:
- name: build rust-amd64-darwin
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/rust-amd64-darwin
    tags:
    - latest
    dockerfile: ./x86_64/darwin/Dockerfile
    context: ./x86_64/darwin/
    registry: docker-registry.k8s.array21.dev

- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust-Docker-Builders
  when:
    status: [ failure ]
---
kind: pipeline
type: docker
name: aarch64-darwin

depends_on:
- generic-darwin

steps:
- name: build rust-aarch64-darwin
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/rust-aarch64-darwin
    tags:
    - latest
    dockerfile: ./aarch64/darwin/Dockerfile
    context: ./aarch64/darwin/
    registry: docker-registry.k8s.array21.dev

- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust-Docker-Builders
  when:
    status: [ failure ]
---
kind: pipeline
type: docker
name: amd64-xenial

steps:
- name: build rust-amd64-xenial
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/rust-amd64-xenial
    tags:
    - latest
    dockerfile: ./x86_64/xenial/Dockerfile
    context: ./x86_64/xenial/
    registry: docker-registry.k8s.array21.dev

- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust-Docker-Builders
  when:
    status: [ failure ]
---
kind: pipeline
type: docker
name: base

steps:
- name: build rust-base
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/rust-base 
    tags:
    - latest
    dockerfile: ./x86_64/ci/Dockerfile
    context: ./x86_64/ci/
    registry: docker-registry.k8s.array21.dev

- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust-Docker-Builders
  when:
    status: [ failure ]
---
kind: pipeline
type: docker
name: amd64-centos7

steps:
- name: build rust-amd64-centos7
  image: plugins/docker
  settings:
    repo: docker-registry.k8s.array21.dev/rust-amd64-centos7
    tags:
    - latest
    dockerfile: ./x86_64/centos7/Dockerfile
    context: ./x86_64/centos7/
    registry: docker-registry.k8s.array21.dev

- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust-Docker-Builders
  when:
    status: [ failure ]
---
kind: pipeline
type: docker
name: generic-darwin

steps:
- name: build generic-darwin
  settings:
    repo: docker-registry.k8s.array21.dev/rust-generic-darwin
    tags:
    - latest
    dockerfile: ./generic/darwin/Dockerfile
    context: ./generic/darwin
    registry: docker-registry.k8s.array21.dev
  
- name: Slack notifications
  image: plugins/slack
  settings:
    webhook:
      from_secret: discord_webhook
    username: Drone CI/CD - Rust-Docker-Builders
  when:
    status: [ failure ]